service: goa


plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: python3.6
  stage: production
  environment:
    BUCKET_NAME:
      Ref: Bucket


functions:


resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
