service: goa


plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'production'}
  environment:
    BUCKET_NAME:
      Ref: Bucket


functions:


resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.namePrefix}-users
        UsernameAttributes:
          - email
        Schema:
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: true

custom:
  namePrefix: goa-${self:provider.stage}
